### ISSUE TITLE
[Bug] No sound after exiting and relaunching

### ISSUE THREAD

**Issue by CloneWith** [petitlapin/Li-Ri#12]
Tried to run Li-Ri on my Android tablet. When I used the builtin *exit* button and relaunched the game, it had no sound output. But by killing the application and launching manually it works.

Some extra info I think may help:

- OS: Android 7.0, EMUI 5.0
- Processor: Snapdragon 435
- Kernel: 3.18.31-g7d66bf5
  - huawei@ubuntu #2
  - Sun Jul 1 04:23:27 CST 2018

**Comment by petitlapin** [comment]
Thank you for reporting the bugs and ideas! I've already noticed this one but didn't find a fix yet. I'll try to fix it when I have spare time
