### ISSUE TITLE
"SDL C/Java version mismatch" on Android

### ISSUE THREAD

**Issue by TheJanzap** [petitlapin/Li-Ri#23]
When launching Li-Ri 3.1.0 via F-Droid on Android 12, I get this error: `SDL C/Java version mismatch (expected 2.28.4, got 2.28.5)`. 
I've already tried to reinstall, but that doesn't help.

**Comment by petitlapin** [comment]
A new version is in progress: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14305, sorry again for the inconvenience.

**Comment by petitlapin** [comment]
The new version has been published, can you confirm if it works better for you?

**Comment by TheJanzap** [comment]
Yes, the game now plays perfectly, thanks for the quick fix! :)
