### ISSUE TITLE
SDL Error on start

### ISSUE THREAD

**Issue by rosenclosed** [petitlapin/Li-Ri#27]
Device Info: 
Manufacturer: Fairphone
Model: FP5 5G
Android: 13
Kernel: 5.4.219-qgki-g50c59753416a (#1 Thu Nov 23 01:37:02 CST 2023)

Application Info: 
Version installed: 3.1.0
Source: F-Droid

When trying to start the application on my device I get the following error: "SDL C/Java Version mismatch (expected 2.28.4, got 2.28.5)

See image:
![Screenshot_20240106-140437](https://github.com/petitlapin/Li-Ri/assets/29880819/80dc976b-98a3-4429-b7a0-67bb02a8ac62)

**Comment by petitlapin** [comment]
Hi,
this is a known issue (https://github.com/petitlapin/Li-Ri/issues/23), I've created a new version 3.1.1 yesterday so it should be present in 2-3 days max in f-droid.

Sorry for the inconvenience.

I'll keep this issue opened until it is released so other people see it (I closed the other one but I should have waited for the release)

**Comment by petitlapin** [comment]
Version 3.1.1 is out, can you confirm it works?

**Comment by petitlapin** [comment]
Fixed in 3.1.1
