### ISSUE TITLE
the game stuck at "press any key" screen

### ISSUE THREAD

**Issue by 25minutes** [petitlapin/Li-Ri#47]
I download the v3.1.4 source code and compile it to run on EmuELEC (https://github.com/EmuELEC/EmuELEC), which is basically a Linux system running on arm device.  gptokeyb (https://github.com/EmuELEC/gptokeyb) is used to map gamepad buttons to keyboard inputs.

I can launch the program successfully, and the gamepad works fine in the menu with the buttons mapped to up/down/left/right/enter/esc.

However, when I try to start the game, it stuck at "press any key" screen. Nothing happens when I press "enter" button or other buttons. The only button that it recongnizes is "esc", with a popup window asking if I want to continue or quit. This popup window accept the "enter" button. 

Does it expect some specific keyboard input to start the game? Any ideas?

**Comment by petitlapin** [comment]
It should work now with any key, sorry for the delay, hope you will now be able to enjoy the game!

**Comment by 25minutes** [comment]
Thanks. It works great!
